## Gradle stuff
#org.gradle.jvmargs=-Xmx8096M
#org.gradle.parallel=true
#org.gradle.caching=true

# Project Details
p_name = TickManipulator
p_id = tick_manipulator
p_group = com.darkmattrmaestro.tick_manipulator
p_desc = Commands and keybinds that make analysing Cosmic Reach tick-by-tick easier.
p_author = DarkMattrMaestro
p_version = 0.2.0

# Cosmic Reach
cosmic_reach_version = 0.6.1-alpha

# Puzzle Loader
puzzle_loader_cosmic_version = 1.7.6-alpha
puzzle_loader_core_version = 1.4.1-alpha

# Puzzle Gradle
puzzle_jigsaw_suite = 1.4.0-beta

# Imgui
imgui_integration_version = 0.6.1-1.0.6